name: Dependency Review

permissions:
  contents: read

on:
  pull_request:
  merge_group:

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/dependency-review-reusable.yml
    with:
      config-file: "windlasstech/.github/.github/dependency-review-config.yml@main"
